[package]
name = "pok3r"
version = "0.0.1"
repository = "https://github.com/rsinha/pok3r"
keywords = ["cryptography", "finite-fields", "elliptic-curves", "pairing"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"
rust-version = "1.63"

################################# Dependencies ################################

[dependencies]
sha2 = "0.9"
criterion = { version = "0.4.0", features = ["html_reports"] }
ark-std = { version = "0.4.0" }
ark-ec = { version = "0.4.0" }
ark-ff = { version = "0.4.0" }
ark-poly = { version = "0.4.0" }
ark-serialize = { version = "^0.4.0", default-features = true }
ark-crypto-primitives = { version = "0.4.0", default-features = false, features = [
    "crh",
] }
num-bigint = { version = "0.4.0", default-features = false }

ark-bls12-377 = { version = "0.4.0", default-features = false, features = [
    "curve",
], optional = true }
ark-bls12-381 = { version = "0.4.0", default-features = false, features = [
    "curve",
], optional = true }

rand = "0.8.5"
rand_chacha = "0.3.1"
paste = { version = "1.0" }
crossbeam = { version = "0.8.2" }
tracing = { version = "0.1", default-features = false, features = [
    "attributes",
] }
tracing-subscriber = { version = "0.2" }

env_logger = "0.10.0"
futures = "0.3.28"
libp2p = { version = "0.52.0", features = [
    "tokio",
    "gossipsub",
    "mdns",
    "noise",
    "macros",
    "tcp",
    "yamux",
] }
libp2p-quic = { version = "0.8.0-alpha", features = ["tokio"] }
clap = { version = "4.3.17", default-features = false, features = [
    "std",
    "derive",
] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "*" }
bs58 = { version = "*" }

tokio = { version = "1.12.0", features = ["full"] }
aws-config = { version = "1", optional = true }
aws-sdk-s3 = { version = "1", optional = true }
aws-sdk-ec2 = { version = "1", optional = true }
aws-sdk-dynamodb = { version = "1", optional = true }
hex = "0.4.3"
anyhow = "1"
reqwest = { version = "0.11.11", default-features = false } #features = ["blocking", "json"]

[features]
default = ["bls12_381"]

asm = ["ark-ff/asm"]
parallel = ["ark-std/parallel", "ark-ff/parallel", "ark-ec/parallel"]
print = []
bls12_381 = ["ark-bls12-381"]
bls12_377 = ["ark-bls12-377"]
aws = ["aws-config", "aws-sdk-s3", "aws-sdk-ec2", "aws-sdk-dynamodb"]

[profile.dev]
opt-level = 3

[[bin]]
name = "load_ip_map"
path = "src/bin/load_ip_map.rs"
required-features = ["aws"]

[[bin]]
name = "print_address_book"
path = "src/bin/print_address_book.rs"
required-features = ["aws"]

[[bin]]
name = "print_deck_dir"
path = "src/bin/print_deck_dir.rs"
required-features = ["aws"]

[[bin]]
name = "print_instance_id"
path = "src/bin/print_instance_id.rs"
required-features = ["aws"]

[[bin]]
name = "read_dynamo_db"
path = "src/bin/read_dynamo_db.rs"
required-features = ["aws"]

[[bin]]
name = "read_pk_dir"
path = "src/bin/read_pk_dir.rs"
required-features = ["aws"]

[[bin]]
name = "run_protocol"
path = "src/bin/run_protocol.rs"
required-features = ["aws"]

[[bin]]
name = "test_pk"
path = "src/bin/test_pk.rs"
required-features = ["aws"]

[[bin]]
name = "update_pk_bucket"
path = "src/bin/update_pk_bucket.rs"
required-features = ["aws"]
