use clap::Parser;
use pok3r::{
    card_id::gen_ids,
    common::{DeckProof, EncryptionInstance, EvalNetMsg, DECK_SIZE, PERM_SIZE},
    evaluator::Evaluator,
    shuffler::{
        compute_decryption_cache, compute_decryption_key, compute_keyper_keys, compute_params,
        compute_permutation_argument, decrypt_one_card, encrypt_and_prove, shuffle_deck,
        verify_deck_proof, verify_encryption_argument, verify_permutation_argument,
    },
};
use tokio::sync::mpsc;

#[cfg(not(feature = "mdns"))]
use pok3r::address_book::generate_address_book_from_port;
#[cfg(feature = "mdns")]
use pok3r::address_book::parse_addr_book_from_json;

/// Simple program to greet a person
#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// Name of the person to greet
    #[arg(short, long)]
    id: String,

    /// Fixed value to generate deterministic peer id
    #[clap(long)]
    seed: u8,

    /// number of parties doing the mpc
    #[clap(long)]
    parties: u64,

    /// port used for parties to communicate (starting with [use base_port + seed_no])
    #[clap(long, default_value_t = 3000)]
    base_port: u16,
}

#[tokio::main]
async fn main() {
    use pok3r::ed25519::generate_ed25519_from_seed;

    let args = Args::parse();
    let parties = args.parties;

    //these channels will connect the evaluator and the network daemons
    let (mut n2e_tx, n2e_rx) = mpsc::unbounded_channel::<EvalNetMsg>();
    let (e2n_tx, e2n_rx) = mpsc::unbounded_channel::<EvalNetMsg>();

    let sk = generate_ed25519_from_seed(args.seed);

    let netd_handle = tokio::spawn(async move {
        // build addr_book inside the netd task
        #[cfg(feature = "mdns")]
        let addr_book = parse_addr_book_from_json(parties);
        #[cfg(not(feature = "mdns"))]
        let addr_book = generate_address_book_from_port(parties, args.base_port);

        let result =
            pok3r::network::run_networking_daemon(sk, &addr_book, &mut n2e_tx, e2n_rx).await;
        if let Err(err) = result {
            eprint!("Networking error {:?}", err);
        }
    });

    #[cfg(feature = "mdns")]
    let addr_book = parse_addr_book_from_json(parties);
    #[cfg(not(feature = "mdns"))]
    let addr_book = generate_address_book_from_port(parties, args.base_port);

    let messaging = pok3r::network::MessagingSystem::new(&args.id, addr_book, e2n_tx, n2e_rx).await;
    let mut mpc = Evaluator::new(messaging, 0);

    //this is a hack until we figure out
    tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
    println!("After sleeping for 1 second.");

    // KZG setup runs once
    let pp = compute_params();

    // Get a random public key pk in G2 - for testing (should be generated by DKG)
    // FIXME: Implement DKG to generate the public key
    let (msk, mpk) = compute_keyper_keys();

    // decrypt all cards
    let cache = compute_decryption_cache();

    for deck_no in 0..20 {
        // Actual protocol
        let mut _card_share_handles = shuffle_deck(&mut mpc).await;

        while _card_share_handles.is_err() {
            println!("failed to generate enough cards, trying again");
            mpc.refresh();
            _card_share_handles = shuffle_deck(&mut mpc).await;
        }
        let card_share_handles = _card_share_handles.unwrap();
        #[cfg(feature = "print")]
        println!(
            "Generated a deck of {} cards after {} attempt(s)",
            card_share_handles.len(),
            mpc.attempt_count()
        );

        let (perm_proof, alpha1) =
            compute_permutation_argument(&pp, &mut mpc, &card_share_handles).await;

        // Get random ids as byte strings
        let ids: Vec<Vec<u8>> = gen_ids(deck_no)
            .iter()
            .map(|id| id.to_bytes().to_vec())
            .collect();

        let instance = EncryptionInstance {
            pk: mpk,
            ids: ids.clone(),
            card_commitment: perm_proof.f_com.clone(),
        };

        // Encrypt and prove
        let (ctxt, encryption_proof) =
            encrypt_and_prove(&pp, &mut mpc, card_share_handles.clone(), alpha1, &mpk).await;

        let mut decrypted_cards = Vec::new();
        for i in 0..PERM_SIZE {
            let dec_key = compute_decryption_key(&ids[i], msk);

            // ignore the first (PERM_SIZE - DECK_SIZE) cards, which are not part of deck
            if i >= (PERM_SIZE - DECK_SIZE) {
                let card = decrypt_one_card(i, &dec_key, &ctxt, &cache).unwrap();
                decrypted_cards.push(card);
                print!("{},", card);
            }
        }

        assert!(
            verify_permutation_argument(&pp, &perm_proof),
            "Permutation argument verification failed"
        );
        assert!(
            verify_encryption_argument(&pp, &ctxt, &encryption_proof, &instance),
            "Encryption proof verification failed"
        );

        let proof = DeckProof {
            perm: perm_proof,
            lec: encryption_proof,
        };
        assert!(
            verify_deck_proof(&pp, &proof, &ctxt, &instance),
            "Combined deck proof proof verification failed"
        );

        // we can verify the proof, but let's also do a sanity check
        // check that decrypted cards is a permutation of 0..51
        let mut sorted_cards = decrypted_cards.clone();
        sorted_cards.sort_unstable();
        let expected_cards: Vec<usize> = (0..DECK_SIZE).collect();
        assert_eq!(
            sorted_cards, expected_cards,
            "Decrypted cards are not a valid permutation of 0..51"
        );
        println!("\ncompleted.");

        mpc = mpc.next();
    }
    let _ = netd_handle.await.unwrap();
}
