#[cfg(not(feature = "aws"))]
use clap::Parser;
use pok3r::card_id::gen_ids;
use pok3r::common::{DeckProof, EncryptionInstance, EvalNetMsg, DECK_SIZE, PERM_SIZE};
use pok3r::evaluator::Evaluator;
use pok3r::shuffler::{
    compute_decryption_cache, compute_decryption_key, compute_keyper_keys, compute_params,
    compute_permutation_argument, decrypt_one_card, encrypt_and_prove, shuffle_deck,
    verify_deck_proof, verify_encryption_argument, verify_permutation_argument,
};
use tokio::sync::mpsc;

/// Simple program to greet a person
#[cfg(not(feature = "aws"))]
#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// Name of the person to greet
    #[arg(short, long)]
    id: String,

    /// Fixed value to generate deterministic peer id
    #[clap(long)]
    seed: u8,

    /// number of parties doing the mpc
    #[clap(long)]
    parties: u64,
}

#[tokio::main]
#[cfg(not(feature = "aws"))]
async fn main() {
    use pok3r::address_book::parse_addr_book_from_json;

    let args = Args::parse();

    //these channels will connect the evaluator and the network daemons
    let (mut n2e_tx, n2e_rx) = mpsc::unbounded_channel::<EvalNetMsg>();
    let (e2n_tx, e2n_rx) = mpsc::unbounded_channel::<EvalNetMsg>();

    let netd_handle = tokio::spawn(async move {
        let result = pok3r::network::run_networking_daemon(
            args.seed,
            &parse_addr_book_from_json(args.parties),
            &mut n2e_tx,
            e2n_rx,
        )
        .await;
        if let Err(err) = result {
            eprint!("Networking error {:?}", err);
        }
    });

    let addr_book = parse_addr_book_from_json(args.parties);
    let messaging = pok3r::network::MessagingSystem::new(&args.id, addr_book, e2n_tx, n2e_rx).await;
    let mut mpc = Evaluator::new(messaging, 0);

    //this is a hack until we figure out
    tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
    println!("After sleeping for 1 second.");

    // KZG setup runs once
    let pp = compute_params();

    // Get a random public key pk in G2 - for testing (should be generated by DKG)
    // FIXME: Implement DKG to generate the public key
    let (msk, mpk) = compute_keyper_keys();

    // decrypt all cards
    let cache = compute_decryption_cache();

    for deck_no in 0..20 {
        // Actual protocol
        let mut _card_share_handles = shuffle_deck(&mut mpc).await;

        while _card_share_handles.is_err() {
            println!("failed to generate enough cards, trying again");
            mpc.refresh();
            _card_share_handles = shuffle_deck(&mut mpc).await;
        }
        let card_share_handles = _card_share_handles.unwrap();
        #[cfg(feature = "print")]
        println!(
            "Generated a deck of {} cards after {} attempt(s)",
            card_share_handles.len(),
            mpc.attempt_count()
        );

        let (perm_proof, alpha1) =
            compute_permutation_argument(&pp, &mut mpc, &card_share_handles).await;

        // Get random ids as byte strings
        let ids: Vec<Vec<u8>> = gen_ids(deck_no)
            .iter()
            .map(|id| id.to_bytes().to_vec())
            .collect();

        let instance = EncryptionInstance {
            pk: mpk,
            ids: ids.clone(),
            card_commitment: perm_proof.f_com.clone(),
        };

        // Encrypt and prove
        let (ctxt, encryption_proof) =
            encrypt_and_prove(&pp, &mut mpc, card_share_handles.clone(), alpha1, &mpk).await;

        let mut decrypted_cards = Vec::new();
        for i in 0..PERM_SIZE {
            let dec_key = compute_decryption_key(&ids[i], msk);

            // ignore the first (PERM_SIZE - DECK_SIZE) cards, which are not part of deck
            if i >= (PERM_SIZE - DECK_SIZE) {
                let card = decrypt_one_card(i, &dec_key, &ctxt, &cache).unwrap();
                decrypted_cards.push(card);
                print!("{},", card);
            }
        }

        assert!(
            verify_permutation_argument(&pp, &perm_proof),
            "Permutation argument verification failed"
        );
        assert!(
            verify_encryption_argument(&pp, &ctxt, &encryption_proof, &instance),
            "Encryption proof verification failed"
        );

        let proof = DeckProof {
            perm: perm_proof,
            lec: encryption_proof,
        };
        assert!(
            verify_deck_proof(&pp, &proof, &ctxt, &instance),
            "Combined deck proof proof verification failed"
        );

        // we can verify the proof, but let's also do a sanity check
        // check that decrypted cards is a permutation of 0..51
        let mut sorted_cards = decrypted_cards.clone();
        sorted_cards.sort_unstable();
        let expected_cards: Vec<usize> = (0..DECK_SIZE).collect();
        assert_eq!(
            sorted_cards, expected_cards,
            "Decrypted cards are not a valid permutation of 0..51"
        );
        println!("\ncompleted.");

        mpc = mpc.next();
    }
    let _ = netd_handle.await.unwrap();
}

#[tokio::main]
#[cfg(feature = "aws")]
async fn main() {
    use libp2p::PeerId;
    use pok3r::address_book::init_address_book_aws;
    use pok3r::aws::{aws_config, init_s3_client, read_deck_s3, save_deck_s3};
    use pok3r::ed25519::read_ed25519_keypair;

    //these channels will connect the evaluator and the network daemons
    let (mut n2e_tx, n2e_rx) = mpsc::unbounded_channel::<EvalNetMsg>();
    let (e2n_tx, e2n_rx) = mpsc::unbounded_channel::<EvalNetMsg>();

    let cfg = aws_config().await;
    let s3_client = init_s3_client(&cfg);
    let address_book = init_address_book_aws(&s3_client).await;

    let keypair = read_ed25519_keypair("/home/ec2-user/pok3r/keypair".to_string())
        .await
        .expect("failed to load keypair");
    let pk = keypair.public();
    let id_b58 = PeerId::from_public_key(&pk).to_base58();

    let book = address_book.clone();

    let netd_handle = tokio::spawn(async move {
        let result = pok3r::network::run_networking_daemon(&book, &mut n2e_tx, e2n_rx).await;
        if let Err(err) = result {
            eprint!("Networking error {:?}", err);
        }
    });

    let messaging =
        pok3r::network::MessagingSystem::new(&id_b58, address_book.clone(), e2n_tx, n2e_rx).await;
    let mut mpc = Evaluator::new(messaging, 0);

    //this is a hack until we figure out
    tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
    println!("After sleeping for 1 second.");

    // KZG setup runs once
    let pp = compute_params();

    // Get a random public key pk in G2 - for testing (should be generated by DKG)
    // FIXME: Implement DKG to generate the public key
    let (msk, mpk) = compute_keyper_keys();

    // decrypt all cards
    let cache = compute_decryption_cache();

    for deck_no in 0..20 {
        // Actual protocol
        let mut _card_share_handles = shuffle_deck(&mut mpc).await;

        while _card_share_handles.is_err() {
            println!("failed to generate enough cards, trying again");
            mpc.refresh();
            _card_share_handles = shuffle_deck(&mut mpc).await;
        }
        let card_share_handles = _card_share_handles.unwrap();
        #[cfg(feature = "print")]
        println!(
            "Generated a deck of {} cards after {} attempt(s)",
            card_share_handles.len(),
            mpc.attempt_count()
        );

        let (perm_proof, alpha1) =
            compute_permutation_argument(&pp, &mut mpc, &card_share_handles).await;

        // Get random ids as byte strings
        let ids: Vec<Vec<u8>> = gen_ids(deck_no)
            .iter()
            .map(|id| id.to_bytes().to_vec())
            .collect();

        let instance = EncryptionInstance {
            pk: mpk,
            ids: ids.clone(),
            card_commitment: perm_proof.f_com.clone(),
        };

        // Encrypt and prove
        let (ctxt, encryption_proof) =
            encrypt_and_prove(&pp, &mut mpc, card_share_handles.clone(), alpha1, &mpk).await;

        let mut decrypted_cards = Vec::new();
        for i in 0..PERM_SIZE {
            let dec_key = compute_decryption_key(&ids[i], msk);

            // ignore the first (PERM_SIZE - DECK_SIZE) cards, which are not part of deck
            if i >= (PERM_SIZE - DECK_SIZE) {
                let card = decrypt_one_card(i, &dec_key, &ctxt, &cache).unwrap();
                decrypted_cards.push(card);
                print!("{},", card);
            }
        }

        assert!(
            verify_permutation_argument(&pp, &perm_proof),
            "Permutation argument verification failed"
        );
        assert!(
            verify_encryption_argument(&pp, &ctxt, &encryption_proof, &instance),
            "Encryption proof verification failed"
        );

        let proof = DeckProof {
            perm: perm_proof,
            lec: encryption_proof,
        };
        assert!(
            verify_deck_proof(&pp, &proof, &ctxt, &instance),
            "Combined deck proof proof verification failed"
        );

        // we can verify the proof, but let's also do a sanity check
        // check that decrypted cards is a permutation of 0..51
        let mut sorted_cards = decrypted_cards.clone();
        sorted_cards.sort_unstable();
        let expected_cards: Vec<usize> = (0..DECK_SIZE).collect();
        assert_eq!(
            sorted_cards, expected_cards,
            "Decrypted cards are not a valid permutation of 0..51"
        );
        println!("\ncompleted.");

        if address_book.get(&id_b58).expect("id not present").node_id == 1 {
            save_deck_s3(&s3_client, deck_no, ctxt.clone(), proof.clone()).await;

            let (deck_aws, proof_aws) = read_deck_s3(&s3_client, deck_no)
                .await
                .expect("failed to get aws deck proof");

            assert!(
                verify_deck_proof(&pp, &proof_aws, &deck_aws, &instance),
                "failed to validate deck and proof from aws"
            );
        }

        mpc = mpc.next();
    }
    let _ = netd_handle.await.unwrap();
}
